
export const YELP = 'u30gFxndwu1hMDTZBPrn0JDZfZV8SIQQzQMcxFhCWpkaawd4wwcLiedTgUFddUFteXzHvfP_8tOLtYVebvZ0BBaeilsaz2P8Vy7CARZ89mXkax8ctIZjvflxDBoDXHYx';
export const GOOGLE = 'AIzaSyCFrrwWmBCPV2bueD6nic1DbtHtFSlbaVc';
